name: repository_mirroring.yml
on: [push]
jobs:
  action-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/B-DOP-200-PAR-2-1-bschocolatine-alfred.ternynck.git
          ssh_private_key:
            ${{ secrets.GITHUB_SSH_PRIVATE_KEY }}
